def test_home(app):
    app.get_html('/', status=200)
    app.get_html('/parameters/2')
    app.get_json('/parameters/2.geojson')
    app.get_dt('/parameters')
    app.get_html('/languages')
    app.get_html('/languages/3')
    app.get_html('/languages/3.snippet.html?parameter=3')
    app.get_json('/languages.geojson')
    app.get_dt('/values?parameter=2')
    app.get_dt('/values?parameter=2&iSortingCols=1&iSortCol_0=0&sSortDir_0=desc')
    app.get_dt('/values?parameter=2&iSortingCols=1&iSortCol_0=1&sSortDir_0=asc')
    app.get_dt('/values?language=2')
    app.get_dt('/values?iSortingCols=1&iSortCol_0=1&sSortDir_0=desc&sSearch_1=a')
    app.get_html('/valuesets/VillarsleTerroir-Gauchat-1925-480-1_ilfait')
